Recruitment/Recruitment/Controllers/FamilyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Recruitment.Models;
using Recruitment.Models.IRepo;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Recruitment.Controllers
{
    public class FamilyController : Controller
    {
        private iFamily _repo;

        public FamilyController(iFamily repo)
        {
            _repo = repo;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public void UpdateFamily(appFamilyBackground data)
        {
            _repo.updateFamily(data);
            //return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public void AddFamily(appFamilyBackground data)
        {
            _repo.insertFamily(data);
           // return RedirectToAction("Index","Home");
        }

        [HttpDelete]
        public void DeleteFamily(int id)
        {
            _repo.deleteFamily(id);
            //return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetFamily(int id)
        {
            var result = _repo.getFamBackground(id);
            return Json(new { data = result });
        }

        [HttpGet]
        public appFamilyViewModel GetSingleFamily(int id)
        {
            var result = _repo.getSingleFamBackground(id);
            // return Json(new { data = result });
            return result;
        }
    }
}

Recruitment/Recruitment/Views/Family/AddFamily.cshtml
@{
    Layout = null;
    var id = @Context.Request.Query["id"];
}
@model Recruitment.Models.appFamilyBackground;

@using (Html.BeginForm("AddFamily", "Family", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.id > 0)
    {
        @Html.HiddenFor(a => a.id)
    }

<div class="card ">
    <input type="text" asp-for="applicantId" value="@id" class="form-control"  required="true">
    <div class="card ">
        <div class="card-header ">
            <h5 class="card-title">Family Background</h5>
        </div>
        <div class="card-body ">
            <div class="row">
                <label class="col-sm-4 col-form-label">Name</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="name" asp-for="name" class="form-control" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Birthdate</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="date" id="birthdate" asp-for="birthDate" class="form-control" placeholder="Birthdate" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Relationship</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="relationship" asp-for="relationship" class="form-control" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Occupation</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="occupation" asp-for="occupation" class="form-control" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">School</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="school" asp-for="school" class="form-control" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Course</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="course" asp-for="course" class="form-control" required="true">
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Contact No</label>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" id="contact" asp-for="contact" class="form-control" placeholder="Contact No" required="true">
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </div>

</div>
}