Recruitment/Recruitment/Models/JobApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recruitment.Models
{
    public class JobApplicationViewModel
    {
        public int id { get; set; }
        public int applicantId { get; set; }
        public string slug { get; set; }
        public string picture { get; set; }
        public string resume { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string jobSlug { get; set; }
        public string dateApplied { get; set; }
        public string dateHired { get; set; }
        public string jobPosition { get; set; }
        public string jobSummary { get; set; }
        public string jobQualifications { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public string branches { get; set; }
        public string department { get; set; }
        public string currentStatus { get; set; }
        public bool passed { get; set; }
    }
}

Recruitment/Recruitment/Models/statuses.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recruitment.Models
{
    public class statuses
    {
        [Key]
        public int id { get; set; }
        public int jobId { get; set; }
        public int applicantId { get; set; }
        public string jobSlug { get; set; }
        public string status { get; set; }
        public DateTime inclusiveDate { get; set; }
        public bool currentStatus { get; set; }
        public bool passed { get; set; }
        public bool sentInvitation { get; set; }
        public bool apointmentDone { get; set; }
        public DateTime createdAt { get; set; }
    }
}

Recruitment/Recruitment/Controllers/JobApplicationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;
using Recruitment.Email;
using Recruitment.Models;
using Recruitment.Models.IRepo;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Recruitment.Controllers
{
    [Authorize]
    public class JobApplicationsController : Controller
    {
        private iJobApplications _repo;
        private iAccountRepository _account;
        private readonly IHostingEnvironment _hostingEnvironment;
        iAdminUsers _sysuser;
        iJobVacancies _jobVac;
        iUserManager _userManager;
        public JobApplicationsController(iJobApplications repo, IHostingEnvironment hostingEnvironment, iAccountRepository account, iAdminUsers sysuser, iJobVacancies jobVac, iUserManager userManager)
        {
            _repo = repo;
            _hostingEnvironment = hostingEnvironment;
            _account = account;
            _sysuser = sysuser;
            _jobVac = jobVac;
            _userManager = userManager;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // GET: /<controller>/
        public IActionResult JobApplications()
        {
            return View();
        }

        

        [HttpPost]
        public void Update(jobApplications data)
        {
            _repo.update(data);
            //return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public void Add(jobApplications data)
        {
            _repo.insert(data);
           // return RedirectToAction("Index","Home");
        }

        [HttpPost]
        public void AddUpdate(jobApplications data)
        {
            _repo.updateBranch(data);
            var acc = _sysuser.getOne(data.applicantId);
            var job = _repo.getOneBySlugApplicant(data.jobSlug, data.applicantId);
            //SEND EMAIL
            var webPage = "https://www.kmbi.org.ph/who-we-are/careers";
            var fbPage = "https://www.facebook.com/KMBIMFNGO";

            var sb = new StringBuilder();
            sb.Append("Dear <b>" + acc.firstName + " " + acc.lastName + "</b>, <br/><br/>");
            sb.Append("We're thrilled that you'd like to join us here at Kabalikat para sa Maunlad na Buhay, Inc. (Microfinance NGO)<br/><br/>");
            sb.Append("We have got your application that you sent us about the <b>" + job.jobPosition + "</b> position. We have looked through some applications as they come in and we will be in touch within two weeks if we'd like to meet you for an interview.<br/><br/>");
            sb.Append("You can read more about us on our company career page <a href='" + webPage + "'>" + webPage + "</a> or follow us on social media on Facebook <a href='" + fbPage + "'>" + fbPage + "</a> to get the latest updates<br/><br/>");
            sb.Append("Masaya dito sa KMBI!<br/><br/>");
            sb.Append("<b>KMBI Online</b><br/><br/>");

            string to = acc.email;
            string subject = "KMBI Online Application";
            string body = sb.ToString();
            bool emailResponse = EmailHelper.SendEmail(to, subject, body, "hcd-staffing@kmbi.org.ph");
            // return RedirectToAction("Index","Home");
        }

        [HttpDelete]
        public void Delete(int id)
        {
            _repo.delete(id);
            //return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetAll()
        {
            var result = _repo.getAll();
            return Json(new { data = result });
        }

        [HttpGet]
        public List<jobApplications> GetAllActive()
        {
            var result = _repo.getAllActive();
            return result;
        }

        [HttpGet]
        public List<jobApplications> PopulateControl()
        {
            var result = _repo.getAll();
            //return Json(new { data = result });
            return result;
        }

        [HttpGet]
        public jobApplications GetOne(int id)
        {
            var result = _repo.getOne(id);
            // return Json(new { data = result });
            return result;
        }

        [HttpGet]
        public jobApplications GetOneSlug(string slug)
        {
            var result = _repo.getOneBySlug(slug);
            // return Json(new { data = result });
            return result;
        }

        [HttpGet]
        public IActionResult AdminList(string branch, string department)
        {
            branch = _userManager.GetCurrentUser(this.HttpContext).branch;
            department = _userManager.GetCurrentUser(this.HttpContext).department;
            var model = _repo.GetAllAdmin(branch, department);
            return View(model);
        }
        
        public IActionResult ApplicantList(int applicantId)
        {
            var model = _repo.GetAllApplicant(applicantId);
            return View(model);
        }

        [HttpGet]
        public IActionResult Statuses(int jobId)
        {
            var model = _repo.GetApplicantStatus(jobId);
            return View(model);
        }

        [HttpGet]
        public IActionResult StatusesHo(int jobId)
        {
            var model = _repo.GetApplicantStatus(jobId);
            return View(model);
        }

        [HttpGet]
        public List<jobApplications> ApplicantApplications(int applicantId)
        {
            var model = _repo.getOneByApplicantId(applicantId);
            return model;
        }

        [HttpGet]
        public bool CheckIfJobExist(string jobSlug, int applicantId, string branch)
        {
            var result = _repo.getOneByJobSlugBranch(jobSlug, applicantId, branch);
            if (result != null)
                return true;
            return false;
        }

        [HttpPost]
        public void UpdateStatus(string status, int id)
        {
            _repo.updateStatus(status, id);
        }

        [HttpGet]
        public IActionResult DownloadPDF(int id)
        {

            var model = _account.getInfoDetails(id);
            
            //Initialize HTML to PDF converter with Blink rendering engine
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter(HtmlRenderingEngine.Blink);

            BlinkConverterSettings blinkConverterSettings = new BlinkConverterSettings();
            string HTMLContent = "<html lang='en'><head>" +
                    "<meta charset='UTF-8'>" +
                    "<meta http-equiv='X-UA-Compatible' content='IE=edge'>" +
                    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                    "<link rel='preconnect' href='https://fonts.gstatic.com'>" +
                    "<link href='https://fonts.googleapis.com/css2?family=Roboto&display=swap' rel='stylesheet'>" +
                    "<title>Title Here</title>" +
                    "<link href=" + Path.Combine(_hostingEnvironment.ContentRootPath, "ReportTemplates/style.css") + " rel='stylesheet' />" +
                    "</head><body>" +
                    "<div class='container'>" +

                    "<table class='header'>" +
                        "<tr>" +
                            "<th rowspan='5' colspan='2' style='width: 22%;'>" +
                                "<div>" +
                                    "<img src='./img/logo.png' alt=''>" +
                                "</div>" +
                                "KMBI <br>(A Microfinance NGO)" +
                            "</th>" +
                            "</th>" +
                            "<th colspan='5' class='form-title'>" +
                                "EMPLOYMENT APPLICATION FORM <br>" +
                                "<small><i>Form No. HCDS-002</i></small>" +
                        "</th>" +
                        "</tr>" +

                        "<tr>" +
                            "<td colspan='3'>Referred by/ thru : " + model.appPersonalData.referredBy + "</td>" +
                            "<td>Date: value here</td>" +
                            "<td rowspan='4' style='width: 13%;'>ID PICTURE (2x2)<br> taken within the last 6 months</td>" +
                        "</tr>" +

                        "<tr>" +
                            "<th colspan='3'>SOCIAL MEDIA ACCOUNTS</th>" +
                            "<th>DESIRED SALARY</th>" +
                        "</tr>" +

                        "<tr>" +
                            "<th>Facebook</th>" +
                            "<th>Instagram</th>" +
                            "<th>Twitter</th>" +
                            "<th></th>" +
                        "</tr>" +

                        "<tr>" +
                            "<th></th>" +
                            "<th></th>" +
                            "<th></th>" +
                            "<th></th>" +
                        "</tr>" +
                    "</table>" +

                    "<table class='personal-data'>" +
                        "<tr>" +
                            "<td class='section-title' rowspan='7'>" +
                            "<div style='text-align:center'>PERSONAL DATA</div>" +
                            "</td>" +
                            "<td colspan='3'><span>FULL NAME</span> (Last Name, First Name, Middle Name) <br> " + model.systemUsers.lastName + ", " + model.systemUsers.firstName + " " + model.systemUsers.middleName + "</td>" +

Recruitment/Recruitment/Views/JobApplications/ApplicantList.cshtml
@using Recruitment.Models.IRepo;
@model List<JobApplicationViewModel>;
@inject iUserManager UserManager;
@{
    bool isAdmin = false;
    isAdmin = UserManager.GetCurrentUser(this.Context).isAdmin;
    var id = UserManager.GetCurrentUser(this.Context).id.ToString();
    string applicantId = @Context.Request.Query["applicantId"];
}
@{
    if (id != applicantId)
    {
        <div class="container-fluid">
            <h1>UNAUTHORIZED ACCESS</h1>
        </div>
    }
    else
    {
        <style>
            .span-texatarea {
                overflow: auto;
                /*height: 8rem;*/
                resize: vertical;
                vertical-align: top !important;
                text-transform: none;
                color: inherit;
                font: inherit;
                border: none;
                outline: 0;
                margin: 0;
                -webkit-appearance: textarea;
                appearance: textarea;
                flex-direction: column !important;
                white-space: pre-wrap !important;
                word-wrap: break-word;
                display: inline-block;
                text-align: start;
                -webkit-writing-mode: horizontal-tb;
            }

            textarea {
                width: 500px;
                height: 150px;
            }
        </style>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">MY APPLICATIONS</h5>

                        </div>
                        <div class="card-body">

                            <table id="datatable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th hidden></th>
                                        <th>Job Applied</th>
                                        <th>Branch</th>
                                        <th>Status</th>
                                        <th>Remarks</th>
                                        <th class="text-center">Cancel</th>
                                        @*<th class="disabled-sorting text-center">View</th>
                                            <th class="disabled-sorting text-center">Cancel</th>*@
                                    </tr>
                                </thead>
                                <tbody>
                                    @{ int ctr = 1;
                                        foreach (var item in Model)
                                        {
                                            var style = "";
                                            var background = "";
                                            var vStatus = "";
                                            if (item.status == "cancelled")
                                            {
                                                style = "disabled";
                                                background = "color: red; font-weight: bold";
                                                vStatus = "cancelled";
                                            }
                                            else
                                            {
                                                vStatus = "active";
                                            }

                                            <tr style="@background">
                                                <td>@ctr</td>
                                                <td hidden>@item.id</td>
                                                <td>@item.jobPosition</td>
                                                <td><div><span class="span-texatarea">@item.branches</span></div></td>
                                                <td>@vStatus</td>
                                                <td>@item.remarks</td>
                                                @*<td><a href="#" class="btn btn-success btn-link btn-sm edit"><i class="fa fa-eye"></i>Details</a></td>*@
                                                @*<td class="text-center"><a href="#" class="btn btn-danger btn-link btn-sm remove" @style><i class="fa fa-ban"></i>Cancel</a></td>*@
                                                <td class="td-actions text-center">
                                                    <a href="#" type="button" rel="tooltip" title="" @style class="btn btn-info btn-round btn-icon btn-icon-mini btn-neutral remove" data-original-title="Cancel Application">
                                                        <i class="nc-icon nc-simple-remove"></i>
                                                    </a>
                                                    @*<button type="button" rel="tooltip" title="" class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Remove">
                                                            <i class="nc-icon nc-simple-remove"></i>
                                                        </button>*@
                                                </td>
                                            </tr>
                                            ctr += 1;
                                        }
                                    }
                                </tbody>

                            </table>
                        </div><!-- end content-->
                    </div><!--  end card  -->
                </div> <!-- end col-md-12 -->
            </div> <!-- end row -->
        </div>

        <script>
            
            $(document).ready(function () {

                $('#datatable').DataTable({
                    "pagingType": "full_numbers",
                    "lengthMenu": [
                        [10, 25, 50, -1],
                        [10, 25, 50, "All"]
                    ],
                    responsive: true,
                    language: {
                        search: "_INPUT_",
                        searchPlaceholder: "Search records",
                    }
                });
                var table = $('#datatable').DataTable();

            // Edit record
                table.on('click', '.edit', function () {
                    $tr = $(this).closest('tr');
                    var data = table.row($tr).data();
                    alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
                });


            // Delete a record
                table.on('click', '.remove', function (e) {
                    $tr = $(this).closest('tr');
                    var data = table.row($tr).data();
                    var id = data[1];
                //alert(data[1]);
                    swal({
                        title: "Are you sure you want to cancel this application?",
                        text: "Confirmation",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Yes",
                        cancelButtonText: "No",
                        closeOnConfirm: false
                    }, function () {
                            swal({
                                title: 'Please Wait..!',
                                text: 'Processing',
                                allowOutsideClick: false,
                                allowEscapeKey: false,
                                allowEnterKey: false,
                                showCancelButton: false,
                                showConfirmButton: false,
                                onOpen: () => {
                                    swal.showLoading()
                                }
                            })
                            $.ajax({
                                type: "POST",
                                url: '@Url.Action("UpdateStatus", "JobApplications")',
                                data: {
                                    status: "cancelled",
                                    id: id
                                },
                                success: function (data) {
                                    swal({
                                        title: "Cancelled!",
                                        text: "",
                                        type: "success",
                                        showCancelButton: false,
                                        confirmButtonColor: "#DD6B55",
                                        confirmButtonText: "OK",
                                        closeOnConfirm: true
                                    }, function () {
                                        location.reload();
                                    });
                                }
                            })
                    });
                });

            });
            </script>
    }
}